---
title: "Practice18"
output: html_document
---


```{r}
library(tidyverse)
```


```{r}
jobs_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv")
earnings_female <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv") 
employed_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv") 
```

```{r}
summarize_jobs_gender <- function(tbl) {
  tbl %>%
      summarize(total_earnings = sum(total_earnings * total_workers) / sum(total_workers),
                total_earnings_male = sum(total_earnings_male * workers_male, na.rm=TRUE) / sum(workers_male[!is.na(total_earnings_male)], na.rm=TRUE),
                total_earnings_female = sum(total_earnings_female * workers_female, na.rm=TRUE)/ sum(workers_female[!is.na(total_earnings_female)], na.rm = TRUE),
                total_workers = sum(total_workers),
                workers_male = sum(workers_male),
                workers_female = sum(workers_female)) %>%
    mutate(wage_percent_of_male = total_earnings_female / total_earnings_male)
}

by_year_major_category <- jobs_gender %>%
  filter(complete.cases(.)) %>%
  group_by(year, major_category) %>%
  summarize_jobs_gender() 


by_year_major_category %>%
  mutate(major_category = fct_reorder(major_category, -total_earnings)) %>%
  ggplot(aes(year, total_earnings, color = major_category)) +
  geom_line() +
  expand_limits(y=0)


by_year_major_category %>%
  mutate(major_category = fct_reorder(major_category, -wage_percent_of_male)) %>%
  ggplot(aes(year, wage_percent_of_male, color = major_category)) +
  geom_line()
```

```{r}
by_minor_category_2016 <- jobs_gender %>%
  filter(year==2016) %>%
  group_by(major_category, minor_category) %>%
  summarize_jobs_gender() %>%
  ungroup()
```

```{r}
by_minor_category_2016 %>%
  mutate(minor_category = fct_reorder(minor_category, wage_percent_of_male)) %>%
  ggplot(aes(minor_category, wage_percent_of_male, fill = major_category)) +
  geom_col(show.legend = FALSE) + 
  coord_flip() 
```

```{r}
p <- jobs_gender %>%
  filter(year == 2016) %>%
  filter(major_category == "Healthcare Practitioners and Technical") %>%
  arrange(desc(wage_percent_of_male)) %>%
  ggplot(aes(total_workers, workers_female/total_workers, color=total_earnings_female/total_earnings_male,
             label=occupation)) +
  geom_point() +
  scale_x_log10() +
  scale_color_gradient2(low = "red", high = "blue", midpoint = 0.85, mid = "pink") +
  labs(x = "Total # of Workers",
       y = "% of Workers") 

library(plotly)
ggplotly(p)
```

```{r}
p <- jobs_gender %>%
  filter(year == 2016) %>%
  filter(major_category == "Computer, Engineering, and Science") %>%
  arrange(desc(wage_percent_of_male)) %>%
  ggplot(aes(total_workers, workers_female/total_workers, color=total_earnings_female/total_earnings_male,
             label=occupation)) +
  geom_point() +
  scale_x_log10() +
  scale_color_gradient2(low = "red", high = "blue", midpoint = 0.85, mid = "pink") +
  labs(x = "Total # of Workers",
       y = "% of Workers") 

library(plotly)
ggplotly(p)
```