---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(scales)
library(ggrepel)

theme_set(theme_light())
```

# LETS LOOK AT SOME GRADUATES YO
```{r}
recent_grads <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-10-16/recent-grads.csv")

majors_processed <- recent_grads %>%
  arrange(desc(Median)) %>%
  mutate(Major = str_to_title(Major), Major = fct_reorder(Major, Median)) 
```
#Category of majors
```{r}
majors_processed %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  ggplot(aes(Major_category, Median, fill = Major_category)) +
  geom_boxplot() +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip() +
  expand_limits(y=0) +
  theme(legend.position = "none")
```
#Highest earning majors
```{r}
majors_processed <- recent_grads %>%
  arrange(desc(Median)) %>%
  select(Major, Major_category, Median, P25th, P75th, Sample_size) %>%
  mutate(Major = str_to_title(Major), Major = fct_reorder(Major, Median)) 

majors_processed %>%
  filter(Sample_size >=100) %>%
  head(20) %>%
  ggplot(aes(Major,Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  coord_flip() +
  labs(title="Highest earning Majors?",
       subtitle = "Top 20 Majors with at least 100 students surveyed, bars are 25th and 75th percentile",
       x="",
       y="Median Salary of Graduates")
```
#Lowest earning majors
```{r}
majors_processed %>%
  tail(20) %>%
  mutate(Major = str_to_title(Major), Major = fct_reorder(Major, Median)) %>%
  ggplot(aes(Major,Median, color = Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin = P25th, ymax = P75th)) +
  coord_flip()
```

```{r}
majors_processed %>%
  ggplot(aes(Sample_size, Median)) +
  geom_point() +
  geom_text(aes(label=Major, check_overlap=TRUE,vjust=1, hjust=1)) +
  scale_x_log10()
```

### Most common majors
```{r}
majors_processed %>%
  mutate(Major_category = fct_reorder(Major, Total)) %>%
  arrange(desc(Total)) %>%
  head(20) %>%
  ggplot(aes(Major_category, Total, fill=Major_category)) +
  geom_col() +
  coord_flip() +
  labs(x="",
       y = "Total Graduates #") +
  scale_y_continuous(labels = comma_format()) +
  theme(legend.position="none")
```
### How does gender breakdown relate to earnings

```{r}
majors_processed %>%
  arrange(desc(Total)) %>%
  head(20) %>%
  mutate(Major = fct_reorder(Major,Total)) %>%
  gather(Gender, Number, Men, Women) %>%
  select(Major, Gender, Number) %>%
  ggplot(aes(Major, Number, fill = Gender)) +
  geom_col() +
  coord_flip()
```

```{r}
by_major_category <- majors_processed %>%
  filter(!is.na(Total)) %>%
  group_by(Major_category) %>%
  summarize(Men = sum(Men),
            Women =sum(Women),
            Total = sum(Total),
            MedianSalary = sum( Median * Sample_size) / sum(Sample_size)) %>%
  mutate(ShareWomen = Women / Total) %>%
  arrange(desc(ShareWomen))
```

```{r}
library(plotly)
g<- by_major_category %>%
  ggplot(aes(ShareWomen, MedianSalary, color=Major_category)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_continuous(label = percent_format())+
  scale_y_continuous(label = dollar_format()) +
  expand_limits(y=0)

ggplotly(g)
```

```{r}
majors_processed %>%
  select(Major, Total, ShareWomen, Sample_size, Median) %>%
  lm(Median ~ ShareWomen, data = ., weights = Sample_size) %>%
  summary()
```

```{r}
library(broom)

majors_processed %>%
  select(Major, Major_category, Total, ShareWomen, Sample_size, Median) %>%
  add_count(Major_category) %>%
  filter(n>=10) %>%
  nest(-Major_category) %>%
  mutate(model = map(data, ~lm(Median ~ ShareWomen, data = ., weights = Sample_size)),
         tidied = map(model,tidy)) %>%
  unnest(tidied) %>%
  filter(term == "ShareWomen") %>%
  arrange(estimate) %>%
  mutate(fdr = p.adjust(p.value, method = "fdr"))
```

