---
title: "Practice14"
output: html_document
---


```{r}
library(tidyverse)
library(forecast)
library(lubridate)
library(timetk)
library(sweep)
```

```{r}
milk_products_facts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milk_products_facts.csv")
```

```{r}
milk_products_tidied <- milk_products_facts %>%
  gather(product, lbs_per_person, -year)

milk_products_tidied %>%
  filter(year == max(year)) %>%
  mutate(product = str_to_title(str_replace_all(product, "_", " ")),
    product = fct_reorder(product, lbs_per_person)) %>%
  ggplot(aes(product, lbs_per_person)) +
  geom_col() +
  coord_flip() +
  labs(x ="",
       y= "Pounds consumed per person")
```

```{r}
 milk_products_tidied <- milk_products_facts %>%
  gather(product, lbs_per_person, -year) %>%
  separate(product, c("category", "product"), sep = "_", 
           extra = "merge",
           fill = "right"
           ) %>%
  mutate(product = coalesce(product, category),
         product = ifelse(product =="other", paste(product, category), product),
         product = str_to_title(str_replace_all(product, "_", " ")),
         category=str_to_title(category)) 

milk_products_tidied %>%
  group_by(category, year) %>%
  summarize(lbs_per_person = sum(lbs_per_person)) %>%
  ggplot(aes(year, lbs_per_person, color = category)) +
  geom_line() +
  labs(title = "Dairy consumption by category",
       x="Year",
       y="Lbs per person")

milk_products_tidied %>%
  group_by(product = fct_lump(product, 6, w=lbs_per_person),
           year) %>%
  summarize(lbs_per_person = sum(lbs_per_person)) %>%
  ggplot(aes(year, lbs_per_person,color = product)) +
  geom_line()

milk_products_tidied %>%
  ggplot(aes(year, lbs_per_person,color = product)) +
  geom_line() +
  facet_wrap(~ product, scales = "free") +
  expand_limits(y=0)


milk_products_tidied %>%
  filter(year == max(year)) %>%
  mutate(product = fct_reorder(product, lbs_per_person, sum)) %>%
  ggplot(aes(product, lbs_per_person, fill = category)) +
  geom_col() +
  coord_flip() +
  labs(x ="",
       y= "Pounds consumed per person")
```

```{r}
milk_product_ts <- milk_products_tidied %>%
  mutate(year = as.Date("0001-01-01") + years(year-1)) %>%
  nest(-category, -product) %>%
  mutate(ts = map(data,tk_ts, start = 1975, freq=1))

```

