---
title: "Practice6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
bridges <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-27/baltimore_bridges.csv") %>%
  mutate(inspection_yr = inspection_yr + 2000) %>%
  mutate(decade = 10 *(yr_built %/% 10))
```

```{r}
head(bridges)
```

```{r}
bridges %>%
  count(carries) %>%
  arrange(desc(n))
```

```{r}
bridges %>%
  filter(yr_built >=1900) %>%
  count(decade = 10 *(yr_built %/% 10), sort=TRUE) %>%
  ggplot(aes(decade, n)) +
  expand_limits(y=0) +
  geom_line()
```

```{r}
bridges %>%
  filter(yr_built >= 1900) %>%
  group_by(decade) %>%
  summarize(pct_good = mean(bridge_condition == "Good"),
            total = n()) %>%
  ggplot(aes(decade, pct_good)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format()) +
  expand_limits(y=0)
```


```{r}
bridges %>%
  count(owner, responsibility)
```

```{r}
bridges %>%
  replace_na(list(responsibility = "Other")) %>%
  count(responsibility = fct_lump(responsibility, 4), sort = TRUE) %>%
  mutate(responsibility = reorder(responsibility,n)) %>%
  ggplot(aes(responsibility,n)) +
  geom_col() +
  coord_flip()
  
```
```{r}
bridges %>%
  filter(yr_built >= 1900) %>%
  replace_na(list(responsibility = "Other")) %>%
  group_by(responsibility = fct_lump(responsibility, 4), decade) %>%
  summarize(pct_good = mean(bridge_condition == "Good"),
            total = n()) %>%
  filter(responsibility != "Other") %>%
  ggplot(aes(decade, pct_good, color = responsibility)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format()) +
  expand_limits(y=0)
```

```{r}
bridges %>%
  ggplot(aes(avg_daily_traffic)) +
  geom_histogram() +
  scale_x_log10(labels = scales::comma_format())
```
```{r}
bridges %>%
  filter(yr_built >= 1900) %>%
  group_by(traffic_category = cut(avg_daily_traffic, c(0, 1000, 10000, Inf),
           labels = c("<1000", "1000-10000", "10000+"))) %>%
  summarize(pct_good = mean(bridge_condition == "Good"),
            total = n())
```

```{r}

```

