---
title: "Practice14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
```

```{r}
agencies <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/agencies.csv")
launches <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/launches.csv")
```

```{r}
launches %>%
  count(launch_year, agency_type) %>%
  ggplot(aes(launch_year, n,color= agency_type)) +
  geom_line() +
  labs(x="Time",
       y="# of launches this year",
       color = "Agency type")
```

```{r}
launches %>%
  count(agency, sort = TRUE)
```

```{r}
launches_processed <- launches %>%
  filter(launch_date <= Sys.Date()) %>%
  mutate(state_code_cleaned = fct_collapse(
    state_code,
    "RU" = c("SU", "RU"),
    "FR" = "F",
    "JP" = "J",
    "IT" = "I"
  )) %>%
  mutate(state_name = countrycode(state_code_cleaned, "iso2c", "country.name"),
         state_name = fct_lump(state_name, 6)) %>%
  replace_na(list(state_name = "Other"))
```

```{r}
launches_processed %>%
  count(launch_year, state_name) %>%
  mutate(state_name = fct_reorder(state_name, -n, sum)) %>%
  ggplot(aes(launch_year, n, color = state_name)) +
  geom_line() +
  labs(x="Time",
       y="Launches per year",
       color = "Responsible state",
       title = "launches per year per country",
       subtitle = "Combines SU (pre 1998) with Russia")
```

```{r}
launches %>%
  count(agency_type, sort = TRUE)
```

```{r}
pravite_startup_launches <- launches_processed %>%
  filter(agency_type %in% c("private", "startup")) %>%
  inner_join(agencies %>%
               select(agency, agency_name = name, short_name, parent),
             by="agency") %>%
  mutate(agency_name_lumped = fct_lump(agency_name, 6),
         agency_name_lumped = if_else(agency_name_lumped == "Other" & state_name == "United States", "Other US", as.character(agency_name_lumped)))
```

```{r}
pravite_startup_launches %>%
  count(agency_name_lumped, state_name, sort = TRUE) %>%
  mutate(agency_name_lumped = fct_reorder(agency_name_lumped, n, sum)) %>%
  ggplot(aes(agency_name_lumped, n, fill = state_name)) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       y = "# of launches",
       title = "Most Active",
       fill = "Country")

pravite_startup_launches %>%
  count(agency_name_lumped, decade = 10*(launch_year %/% 10)) %>%
  complete(agency_name_lumped, decade, fill = list(n=0)) %>%
  mutate(agency_name_lumped = fct_reorder(agency_name_lumped, n, sum)) %>%
  ggplot(aes(decade, n, color = agency_name_lumped)) +
  geom_line() +
  facet_wrap(~agency_name_lumped) +  
  theme(legend.position = "none") +
  labs (x="time",
        y="# of launches")
  
```

```{r}
vehicles <- launches_processed %>%
  group_by(type, state_name) %>%
  summarize(first_launch = min(launch_year),
            last_launch = max(launch_year),
            launches = n()) %>%
  ungroup() 


russian_vehicles <- vehicles %>%
  filter(state_name == "Russia") %>%
  arrange(desc(launches)) %>%
  filter(launches >=30)

launches_processed %>% 
  semi_join(russian_vehicles, by = "type") %>%
  mutate(type = fct_reorder(type, launch_date, min)) %>%
  ggplot(aes(launch_date, type)) +
  geom_jitter(color = "blue", alpha =.3, width = 0, height =.2)

launches_processed %>% 
  semi_join(russian_vehicles, by = "type") %>%
  mutate(type = fct_reorder(type, launch_date, min)) %>%
  ggplot(aes(launch_date, type, fill = type)) +
  geom_boxplot() +
  labs(x="year",
       y="vehcile",
       title = "timeline of russian space flyers")
```

```{r}
launches_processed %>% 
  filter(state_code == "US") %>%
  add_count(type) %>%
  filter(n >= 20) %>%
  mutate(type = fct_reorder(type, launch_date, min)) %>%
  ggplot(aes(launch_date, type, color = agency_type)) +
  geom_jitter(alpha =.3, width = 0, height =.2)

```

