---
title: "Silge3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
```

```{r}
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')

food_consumption
```

```{r}
library(countrycode)

food <- food_consumption %>%
  mutate(continent = countrycode(country, origin = "country.name",
                                 destination = "continent")) %>%
  select(-co2_emmission) %>%
  pivot_wider(names_from = food_category,
              values_from = consumption) %>%
  janitor::clean_names() %>%
  mutate(asia = case_when(continent =="Asia" ~ "Asia",
                          TRUE ~ "Other")) %>%
  select(-country, -continent) %>%
  mutate_if(is.character, factor)
  
```

```{r}
library(GGally)

ggscatmat(food, columns = 1:11, color ="asia", alpha = 0.6)
```

## Hyperparameter tuning

```{r}
library(tidymodels)
set.seed(1234)

food_boot <- bootstraps(food, times = 30)
```

```{r}
rf_spec <- rand_forest(mode = "classification", 
            mtry = tune(),
            trees = 1000,
            min_n = tune()) %>%
  set_engine("ranger")


rf_grid <- tune_grid(rf_spec,
  asia ~ .,
  resamples = food_boot
)
```

```{r}
rf_grid %>%
  show_best("roc_auc")
```

